# Generated by Django 6.0.4 on 2026-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numControl', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('primerAp', models.CharField(max_length=100)),
                ('segundoAp', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('semestre', models.IntegerField()),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
